version: '3'
services:
  test-db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: activitypub-test
      MYSQL_ROOT_PASSWORD: activitypub-test
    expose:
      - "3306"

  test-php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - test-db
    volumes:
      - .:/app
    command: ["composer", "run-script", "test"]
