<?php
/**
 * FASP controller file.
 *
 * @package Activitypub
 */

namespace Activitypub\Rest;

use Activitypub\Fasp;
use Activitypub\Signature;
use Activitypub\Signature\Http_Message_Signature;

/**
 * ActivityPub FASP Controller.
 *
 * Implements the Fediverse Auxiliary Service Provider (FASP) specification v0.1,
 * including both provider info and registration endpoints.
 *
 * @see https://github.com/mastodon/fediverse_auxiliary_service_provider_specifications/tree/main/general/v0.1
 * @see https://github.com/mastodon/fediverse_auxiliary_service_provider_specifications/blob/main/general/v0.1/registration.md
 */
class Fasp_Controller extends \WP_REST_Controller {
	/**
	 * The namespace of this controller's route.
	 *
	 * @var string
	 */
	protected $namespace = ACTIVITYPUB_REST_NAMESPACE;

	/**
	 * The REST base for this controller's route.
	 *
	 * @var string
	 */
	protected $rest_base = 'fasp';

	/**
	 * Register routes.
	 */
	public function register_routes() {
		\register_rest_route(
			$this->namespace,
			'/' . $this->rest_base . '/provider_info',
			array(
				array(
					'methods'             => \WP_REST_Server::READABLE,
					'callback'            => array( $this, 'get_provider_info' ),
					'permission_callback' => array( 'Activitypub\Rest\Server', 'verify_signature' ),
				),
				'schema' => array( $this, 'get_provider_info_schema' ),
			)
		);

		// Registration endpoint for FASP providers to register with this server.
		\register_rest_route(
			$this->namespace,
			'/' . $this->rest_base . '/registration',
			array(
				array(
					'methods'             => \WP_REST_Server::CREATABLE,
					'callback'            => array( $this, 'handle_registration' ),
					'permission_callback' => array( $this, 'registration_permission_check' ),
					'args'                => array(
						'name'      => array(
							'required'          => true,
							'type'              => 'string',
							'description'       => 'The name of the FASP.',
							'sanitize_callback' => 'sanitize_text_field',
						),
						'baseUrl'   => array(
							'required'          => true,
							'type'              => 'string',
							'format'            => 'uri',
							'description'       => 'The base URL of the FASP.',
							'sanitize_callback' => 'esc_url_raw',
						),
						'serverId'  => array(
							'required'          => true,
							'type'              => 'string',
							'description'       => 'The server ID generated by the FASP.',
							'sanitize_callback' => 'sanitize_text_field',
						),
						'publicKey' => array(
							'required'          => true,
							'type'              => 'string',
							'description'       => 'The FASP public key, base64 encoded.',
							'sanitize_callback' => 'sanitize_text_field',
						),
					),
				),
				'schema' => array( $this, 'get_registration_schema' ),
			)
		);

		// Capability activation endpoint (enable).
		\register_rest_route(
			$this->namespace,
			'/' . $this->rest_base . '/capabilities/(?P<identifier>[a-zA-Z0-9_-]+)/(?P<version>[0-9]+(?:\.[0-9]+)*)/activation',
			array(
				array(
					'methods'             => \WP_REST_Server::CREATABLE,
					'callback'            => array( $this, 'enable_capability' ),
					'permission_callback' => array( 'Activitypub\Rest\Server', 'verify_signature' ),
					'args'                => array(
						'identifier' => array(
							'required'    => true,
							'type'        => 'string',
							'description' => 'The capability identifier.',
						),
						'version'    => array(
							'required'    => true,
							'type'        => 'string',
							'pattern'     => '^\d+(?:\.\d+)*$',
							'description' => 'The capability version.',
						),
					),
				),
			)
		);

		// Capability deactivation endpoint (disable).
		\register_rest_route(
			$this->namespace,
			'/' . $this->rest_base . '/capabilities/(?P<identifier>[a-zA-Z0-9_-]+)/(?P<version>[0-9]+(?:\.[0-9]+)*)/activation',
			array(
				array(
					'methods'             => \WP_REST_Server::DELETABLE,
					'callback'            => array( $this, 'disable_capability' ),
					'permission_callback' => array( 'Activitypub\Rest\Server', 'verify_signature' ),
					'args'                => array(
						'identifier' => array(
							'required'    => true,
							'type'        => 'string',
							'description' => 'The capability identifier.',
						),
						'version'    => array(
							'required'    => true,
							'type'        => 'string',
							'pattern'     => '^\d+(?:\.\d+)*$',
							'description' => 'The capability version.',
						),
					),
				),
			)
		);
	}

	/**
	 * Get provider info.
	 *
	 * @param \WP_REST_Request $request The REST request.
	 * @return \WP_REST_Response|\WP_Error The response or error.
	 */
	public function get_provider_info( $request ) { // phpcs:ignore VariableAnalysis.CodeAnalysis.VariableAnalysis.UnusedVariable
		// Build provider name.
		$site_name = \get_bloginfo( 'name' );
		$name      = $site_name ? $site_name . ' ActivityPub FASP' : 'WordPress ActivityPub FASP';

		// Build privacy policy.
		$privacy_policy     = array();
		$privacy_policy_url = \get_privacy_policy_url();
		if ( $privacy_policy_url ) {
			$privacy_policy = array(
				array(
					'url'      => $privacy_policy_url,
					'language' => \get_locale(),
				),
			);
		}

		// Get capabilities - can be extended by filters.
		$capabilities = \apply_filters( 'activitypub_fasp_capabilities', array() );

		// Build provider info.
		$provider_info = array(
			'name'          => $name,
			'privacyPolicy' => $privacy_policy,
			'capabilities'  => $capabilities,
			'signInUrl'     => \admin_url(),
			'contactEmail'  => \get_option( 'admin_email' ),
		);

		$response = new \WP_REST_Response( $provider_info );

		// Add content-digest header as required by specification.
		$content = \wp_json_encode( $provider_info );
		$digest  = ( new Http_Message_Signature() )->generate_digest( $content );
		$response->header( 'Content-Digest', $digest );

		// Sign the response.
		$this->sign_response( $response, $content );

		return $response;
	}

	/**
	 * Sign the response using HTTP Message Signatures (RFC-9421) with Ed25519.
	 *
	 * Uses the server's Ed25519 keypair as required by the FASP specification.
	 *
	 * @param \WP_REST_Response $response The response to sign.
	 * @param string            $content  The response content (unused, for future use).
	 */
	private function sign_response( $response, $content ) { // phpcs:ignore VariableAnalysis.CodeAnalysis.VariableAnalysis.UnusedVariable
		$keypair     = Signature::get_server_ed25519_keypair();
		$private_key = $keypair['private'];

		/*
		 * Use the site URL as the key ID for FASP signatures.
		 * This matches the serverId concept in the FASP spec.
		 */
		$key_id = \trailingslashit( \get_home_url() ) . '#fasp-key';

		$signature_helper = new Http_Message_Signature();
		$signature_helper->sign_response_ed25519(
			$response,
			$private_key,
			$key_id,
			'sig'
		);
	}

	/**
	 * Handle FASP registration requests.
	 *
	 * @param \WP_REST_Request $request The REST request.
	 * @return \WP_REST_Response|\WP_Error The response or error.
	 */
	public function handle_registration( $request ) {
		// Get the server's Ed25519 public key as required by the FASP spec.
		$public_key = Signature::get_server_ed25519_public_key();

		// Generate unique FASP ID.
		$fasp_id = $this->generate_unique_id();

		// Parameters are already sanitized via sanitize_callback in register_routes().
		$fasp_public_key = $request->get_param( 'publicKey' );

		// Store registration request (pending approval).
		$registration_data = array(
			'fasp_id'                     => $fasp_id,
			'name'                        => $request->get_param( 'name' ),
			'base_url'                    => $request->get_param( 'baseUrl' ),
			'server_id'                   => $request->get_param( 'serverId' ),
			'fasp_public_key'             => $fasp_public_key,
			'fasp_public_key_fingerprint' => Fasp::get_public_key_fingerprint( $fasp_public_key ),
			'server_public_key'           => $public_key,
			'status'                      => 'pending',
			'requested_at'                => \current_time( 'mysql', true ),
		);

		$result = $this->store_registration_request( $registration_data );
		if ( ! $result ) {
			return new \WP_Error(
				'storage_failed',
				'Failed to store registration request',
				array( 'status' => 500 )
			);
		}

		// Generate registration completion URI.
		$completion_uri = \admin_url( 'admin.php?page=activitypub-fasp-registrations&highlight=' . \rawurlencode( $fasp_id ) );

		// Return successful response with the server's Ed25519 public key.
		$response_data = array(
			'faspId'                    => $fasp_id,
			'publicKey'                 => $public_key,
			'registrationCompletionUri' => $completion_uri,
		);

		return new \WP_REST_Response( $response_data, 201 );
	}

	/**
	 * Enable a capability for a FASP.
	 *
	 * @param \WP_REST_Request $request The REST request.
	 * @return \WP_REST_Response|\WP_Error The response or error.
	 */
	public function enable_capability( $request ) {
		$validation = $this->validate_capability_request( $request );
		if ( \is_wp_error( $validation ) ) {
			return $validation;
		}

		$result = $this->enable_fasp_capability(
			$validation['fasp_id'],
			$validation['identifier'],
			$validation['version']
		);

		if ( ! $result ) {
			return new \WP_Error(
				'capability_update_failed',
				'Failed to enable capability',
				array( 'status' => 500 )
			);
		}

		return new \WP_REST_Response( null, 204 );
	}

	/**
	 * Disable a capability for a FASP.
	 *
	 * @param \WP_REST_Request $request The REST request.
	 * @return \WP_REST_Response|\WP_Error The response or error.
	 */
	public function disable_capability( $request ) {
		$validation = $this->validate_capability_request( $request );
		if ( \is_wp_error( $validation ) ) {
			return $validation;
		}

		$result = $this->disable_fasp_capability(
			$validation['fasp_id'],
			$validation['identifier'],
			$validation['version']
		);

		if ( ! $result ) {
			return new \WP_Error(
				'capability_update_failed',
				'Failed to disable capability',
				array( 'status' => 500 )
			);
		}

		return new \WP_REST_Response( null, 204 );
	}

	/**
	 * Validate a capability request and return the validated data.
	 *
	 * Per FASP spec, the keyId in the signature MUST be the serverId exchanged during registration.
	 * Signature verification is handled by the permission callback (Server::verify_signature).
	 *
	 * @param \WP_REST_Request $request The REST request.
	 * @return array|\WP_Error Validated data or error.
	 */
	private function validate_capability_request( $request ) {
		$identifier = $request->get_param( 'identifier' );
		$version    = $request->get_param( 'version' );

		// Extract keyId (serverId) from request headers.
		// Signature is already verified by Server::verify_signature permission callback.
		$headers = $request->get_headers();
		$keyid   = $this->extract_keyid_from_request( $headers );
		if ( \is_wp_error( $keyid ) ) {
			return $keyid;
		}

		// Look up FASP registration by serverId.
		$fasp_data = $this->get_fasp_by_keyid( $keyid );
		if ( \is_wp_error( $fasp_data ) ) {
			return $fasp_data;
		}

		// Verify FASP is approved.
		if ( 'approved' !== $fasp_data['status'] ) {
			return new \WP_Error(
				'fasp_not_approved',
				'FASP registration is not approved',
				array( 'status' => 403 )
			);
		}

		// Check if capability is supported.
		$supported_capabilities = $this->get_supported_capabilities_list();
		$capability_key         = $identifier . '_v' . $version;

		if ( ! isset( $supported_capabilities[ $capability_key ] ) ) {
			return new \WP_Error(
				'capability_not_found',
				'Capability not found or not supported',
				array( 'status' => 404 )
			);
		}

		return array(
			'fasp_id'    => $fasp_data['fasp_id'],
			'identifier' => $identifier,
			'version'    => $version,
		);
	}

	/**
	 * Permission check for registration endpoint.
	 *
	 * @param \WP_REST_Request $request The REST request.
	 * @return bool True if allowed.
	 */
	public function registration_permission_check( $request ) { // phpcs:ignore VariableAnalysis.CodeAnalysis.VariableAnalysis.UnusedVariable
		// Registration endpoint is publicly accessible but should verify.
		// the request comes from a legitimate FASP.
		return true;
	}

	/**
	 * Generate unique ID for FASP.
	 *
	 * @return string Unique ID.
	 */
	private function generate_unique_id() {
		return \wp_generate_password( 12, false );
	}

	/**
	 * Store registration request using WordPress options.
	 *
	 * @param array $data Registration data.
	 * @return bool True on success, false on failure.
	 */
	private function store_registration_request( $data ) {
		$registrations = $this->get_registration_records();

		// Add new registration.
		$registrations[ $data['fasp_id'] ] = $data;

		// Store updated registrations without autoloading.
		return \update_option( 'activitypub_fasp_registrations', $registrations, false );
	}

	/**
	 * Get existing registration records, ensuring the option exists and is sanitized.
	 *
	 * @return array Registration records.
	 */
	private function get_registration_records() {
		$registrations = \get_option( 'activitypub_fasp_registrations', null );

		if ( null === $registrations ) {
			\add_option( 'activitypub_fasp_registrations', array(), '', 'no' );
			return array();
		}

		if ( ! is_array( $registrations ) ) {
			$registrations = array();
		}

		return $this->sanitize_registration_records( $registrations );
	}

	/**
	 * Remove sensitive data from stored registrations.
	 *
	 * @param array $registrations Registration records.
	 * @return array Sanitized registration records.
	 */
	private function sanitize_registration_records( array $registrations ) {
		$modified = false;

		foreach ( $registrations as $fasp_id => $registration ) {
			if ( isset( $registration['server_private_key'] ) ) {
				unset( $registration['server_private_key'] );
				$registrations[ $fasp_id ] = $registration;
				$modified                  = true;
			}

			if ( isset( $registration['fasp_public_key'] ) && empty( $registration['fasp_public_key_fingerprint'] ) ) {
				$registration['fasp_public_key_fingerprint'] = Fasp::get_public_key_fingerprint( $registration['fasp_public_key'] );
				$registrations[ $fasp_id ]                   = $registration;
				$modified                                    = true;
			}
		}

		if ( $modified ) {
			\update_option( 'activitypub_fasp_registrations', $registrations, false );
		}

		return $registrations;
	}

	/**
	 * Extract keyId from request headers.
	 *
	 * @param array $headers The request headers.
	 * @return string|\WP_Error The keyId or error.
	 */
	private function extract_keyid_from_request( $headers ) {
		// Try RFC-9421 Signature-Input header first.
		if ( isset( $headers['signature_input'][0] ) ) {
			if ( \preg_match( '/keyid="([^"]+)"/', $headers['signature_input'][0], $matches ) ) {
				return $matches[1];
			}
		}

		// Try legacy Authorization/Signature header.
		if ( isset( $headers['signature'][0] ) ) {
			if ( \preg_match( '/keyId="([^"]+)"/', $headers['signature'][0], $matches ) ) {
				return $matches[1];
			}
		}

		if ( isset( $headers['authorization'][0] ) ) {
			if ( \preg_match( '/keyId="([^"]+)"/', $headers['authorization'][0], $matches ) ) {
				return $matches[1];
			}
		}

		return new \WP_Error(
			'missing_keyid',
			'Missing keyId in signature headers',
			array( 'status' => 401 )
		);
	}

	/**
	 * Look up FASP registration by keyId (serverId).
	 *
	 * Per FASP spec, the keyId MUST be the identifier exchanged during registration (serverId).
	 *
	 * @see https://github.com/mastodon/fediverse_auxiliary_service_provider_specifications/blob/main/general/v0.1/protocol_basics.md
	 *
	 * @param string $keyid The keyId from the signature (should be the serverId).
	 * @return array|\WP_Error FASP data or error.
	 */
	private function get_fasp_by_keyid( $keyid ) {
		$registration = Fasp::get_registration_by_server_id( $keyid );

		if ( ! $registration ) {
			return new \WP_Error(
				'fasp_not_found',
				'FASP not found for provided keyId',
				array( 'status' => 404 )
			);
		}

		return $registration;
	}

	/**
	 * Get supported capabilities list.
	 *
	 * @return array Supported capabilities.
	 */
	private function get_supported_capabilities_list() {
		$capabilities = (array) \apply_filters( 'activitypub_fasp_capabilities', array() );
		$indexed      = array();

		foreach ( $capabilities as $capability ) {
			if ( empty( $capability['id'] ) || ! isset( $capability['version'] ) ) {
				continue;
			}

			$key             = $capability['id'] . '_v' . $capability['version'];
			$indexed[ $key ] = $capability;
		}

		return $indexed;
	}

	/**
	 * Enable a capability for a FASP.
	 *
	 * @param string $fasp_id    FASP ID.
	 * @param string $identifier Capability identifier.
	 * @param int    $version    Capability version.
	 * @return bool True on success, false on failure.
	 */
	private function enable_fasp_capability( $fasp_id, $identifier, $version ) {
		// Get existing capabilities.
		$capabilities = $this->get_capability_records();

		// Create capability key.
		$capability_key = $fasp_id . '_' . $identifier . '_v' . $version;

		// Enable capability.
		$capabilities[ $capability_key ] = array(
			'fasp_id'    => $fasp_id,
			'identifier' => $identifier,
			'version'    => $version,
			'enabled'    => true,
			'updated_at' => current_time( 'mysql', true ),
		);

		// Store updated capabilities.
		return \update_option( 'activitypub_fasp_capabilities', $capabilities, false );
	}

	/**
	 * Disable a capability for a FASP.
	 *
	 * @param string $fasp_id    FASP ID.
	 * @param string $identifier Capability identifier.
	 * @param int    $version    Capability version.
	 * @return bool True on success, false on failure.
	 */
	private function disable_fasp_capability( $fasp_id, $identifier, $version ) {
		// Get existing capabilities.
		$capabilities = $this->get_capability_records();

		// Create capability key.
		$capability_key = $fasp_id . '_' . $identifier . '_v' . $version;

		// Disable capability.
		if ( isset( $capabilities[ $capability_key ] ) ) {
			$capabilities[ $capability_key ]['enabled']    = false;
			$capabilities[ $capability_key ]['updated_at'] = current_time( 'mysql', true );
		}

		// Store updated capabilities.
		return \update_option( 'activitypub_fasp_capabilities', $capabilities, false );
	}

	/**
	 * Retrieve stored capability assignments, ensuring the option exists and is non-autoloaded.
	 *
	 * @return array
	 */
	private function get_capability_records() {
		$capabilities = \get_option( 'activitypub_fasp_capabilities', null );

		if ( null === $capabilities ) {
			\add_option( 'activitypub_fasp_capabilities', array(), '', 'no' );
			return array();
		}

		if ( ! is_array( $capabilities ) ) {
			return array();
		}

		return $capabilities;
	}

	/**
	 * Get the schema for provider info endpoint.
	 *
	 * @return array The schema.
	 */
	public function get_provider_info_schema() {
		return array(
			'$schema'    => 'http://json-schema.org/draft-04/schema#',
			'title'      => 'FASP Provider Info',
			'type'       => 'object',
			'properties' => array(
				'name'             => array(
					'type'        => 'string',
					'description' => 'The name of the FASP provider.',
				),
				'privacyPolicy'    => array(
					'type'        => 'array',
					'description' => 'Privacy policy information.',
					'items'       => array(
						'type'       => 'object',
						'properties' => array(
							'url'      => array(
								'type'   => 'string',
								'format' => 'uri',
							),
							'language' => array(
								'type' => 'string',
							),
						),
					),
				),
				'capabilities'     => array(
					'type'        => 'array',
					'description' => 'Supported capabilities.',
					'items'       => array(
						'type'       => 'object',
						'properties' => array(
							'id'      => array(
								'type' => 'string',
							),
							'version' => array(
								'type' => 'string',
							),
						),
					),
				),
				'signInUrl'        => array(
					'type'        => 'string',
					'format'      => 'uri',
					'description' => 'URL where administrators can sign in.',
				),
				'contactEmail'     => array(
					'type'        => 'string',
					'format'      => 'email',
					'description' => 'Contact email address.',
				),
				'fediverseAccount' => array(
					'type'        => 'string',
					'description' => 'Fediverse account for updates.',
				),
			),
			'required'   => array( 'name', 'privacyPolicy', 'capabilities' ),
		);
	}

	/**
	 * Get the schema for registration endpoint.
	 *
	 * @return array The schema.
	 */
	public function get_registration_schema() {
		return array(
			'$schema'    => 'http://json-schema.org/draft-04/schema#',
			'title'      => 'FASP Registration Request',
			'type'       => 'object',
			'properties' => array(
				'name'      => array(
					'type'        => 'string',
					'description' => 'The name of the FASP provider.',
				),
				'baseUrl'   => array(
					'type'        => 'string',
					'format'      => 'uri',
					'description' => 'The base URL of the FASP provider.',
				),
				'serverId'  => array(
					'type'        => 'string',
					'description' => 'The server ID generated by the FASP.',
				),
				'publicKey' => array(
					'type'        => 'string',
					'description' => 'The FASP public key, base64 encoded.',
				),
			),
			'required'   => array( 'name', 'baseUrl', 'serverId', 'publicKey' ),
		);
	}
}
