#!/usr/bin/env sh

# Run the WordPress formatter with our custom plugin
echo "Running wp-scripts format..."
npm run format

# If the script made changes, add those changes to the commit
if [ $? -eq 0 ]; then
  # Re-add any files that were modified by the formatter
  git diff --name-only | xargs -r git add
fi
