name: PHP_CodeSniffer
on:
  push:
    branches:
      - trunk
    paths:
      - '**/*.php'
      - 'composer.json'
      - 'composer.lock'
      - 'phpunit.xml.dist'
      - 'phpcs.xml'
      - '.github/workflows/phpcs.yml'
      - '!build/**/*.asset.php'
  pull_request:
    paths:
      - '**/*.php'
      - 'composer.json'
      - 'composer.lock'
      - 'phpunit.xml.dist'
      - 'phpcs.xml'
      - '.github/workflows/phpcs.yml'
      - '!build/**/*.asset.php'
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer, cs2pr
      - name: Install Composer dependencies for PHP
        uses: ramsey/composer-install@26d8a556604053a9612623447203a691f406fbe6 # v4
      - name: Detect coding standard violations
        run: ./vendor/bin/phpcs
